"""
pr_agent.py
Opens a GitHub PR automatically after a self-healing event.

What it does:
  1. Creates a new branch  fix/lambda-<issue_type>-<timestamp>
  2. Commits an updated lambda_config.json with the new timeout/memory
  3. Opens a PR with a structured description — root cause, fix, metrics snapshot

Requirements:
  GITHUB_TOKEN  — personal access token with repo scope
  GITHUB_REPO   — e.g. "abiramikannanofficial-dotcom/self-healing-starter"
  GITHUB_BRANCH — base branch to PR against (default: "develop")

All three can live in .env alongside your AWS credentials.
"""

import os
import json
import base64
import requests
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()

GITHUB_API   = "https://api.github.com"
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO  = os.getenv("GITHUB_REPO", "")
BASE_BRANCH  = os.getenv("GITHUB_BRANCH", "develop")


def _headers():
    return {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept":        "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _raise(resp, context=""):
    if not resp.ok:
        raise RuntimeError(f"GitHub API error{' (' + context + ')' if context else ''}: "
                           f"{resp.status_code} — {resp.text[:300]}")


# ── Low-level GitHub helpers ──────────────────────────────────────────────────

def _get_base_sha(repo: str, branch: str) -> str:
    """Return the latest commit SHA on the base branch."""
    r = requests.get(f"{GITHUB_API}/repos/{repo}/git/ref/heads/{branch}", headers=_headers())
    _raise(r, "get_base_sha")
    return r.json()["object"]["sha"]


def _create_branch(repo: str, new_branch: str, sha: str):
    """Create a new branch from a given commit SHA."""
    payload = {"ref": f"refs/heads/{new_branch}", "sha": sha}
    r = requests.post(f"{GITHUB_API}/repos/{repo}/git/refs", headers=_headers(), json=payload)
    if r.status_code == 422 and "already exists" in r.text:
        return  # branch already exists — fine
    _raise(r, "create_branch")


def _get_file_sha(repo: str, path: str, branch: str):
    """Return the blob SHA of an existing file (needed to update it). None if not found."""
    r = requests.get(
        f"{GITHUB_API}/repos/{repo}/contents/{path}",
        headers=_headers(),
        params={"ref": branch},
    )
    if r.status_code == 404:
        return None
    _raise(r, "get_file_sha")
    return r.json().get("sha")


def _upsert_file(repo: str, branch: str, path: str, content: str, message: str):
    """Create or update a file on the given branch."""
    existing_sha = _get_file_sha(repo, path, branch)
    payload = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch":  branch,
    }
    if existing_sha:
        payload["sha"] = existing_sha

    r = requests.put(
        f"{GITHUB_API}/repos/{repo}/contents/{path}",
        headers=_headers(),
        json=payload,
    )
    _raise(r, "upsert_file")


def _open_pr(repo: str, title: str, body: str, head: str, base: str) -> dict:
    """Open a pull request. Returns the PR dict from GitHub."""
    payload = {
        "title": title,
        "body":  body,
        "head":  head,
        "base":  base,
    }
    r = requests.post(f"{GITHUB_API}/repos/{repo}/pulls", headers=_headers(), json=payload)
    _raise(r, "open_pr")
    return r.json()


# ── PR body builder ───────────────────────────────────────────────────────────

def _build_pr_body(detection: dict, diagnosis: dict, fix_result: dict, outcome: str, repo: str = "") -> str:
    fn   = detection["function_name"]
    cfg  = detection["config"]
    mtr  = detection["metrics"]
    issues = detection.get("issues", [])
    params = diagnosis.get("fix_params", {})

    issue_lines = "\n".join(
        f"- `[{i['severity']}]` **{i['type']}** — {i['detail']}" for i in issues
    ) or "- None"

    reasoning = "\n".join(
        f"{idx+1}. {step}" for idx, step in enumerate(diagnosis.get("reasoning", []))
    )

    old_timeout = cfg.get("timeout", "?")
    old_memory  = cfg.get("memory",  "?")
    new_timeout = params.get("timeout") or fix_result.get("new_timeout") or old_timeout
    new_memory  = params.get("memory")  or fix_result.get("new_memory")  or old_memory

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    outcome_section = (
        f"✅ **Fix applied successfully** at {timestamp}"
        if outcome == "applied"
        else f"⚠️ **Fix was proposed but not applied** (outcome: `{outcome}`)"
    )

    return f"""## 🤖 Self-Healing — Automated Fix

> Generated by the Agentic DevOps dashboard · {timestamp}

---

### 📋 Function
| Field | Value |
|---|---|
| Name | `{fn}` |
| Runtime | `{cfg.get('runtime', '?')}` |
| Region | `{detection.get('config', {}).get('last_modified', '?')}` |

---

### ⚠️ Detected Issues
{issue_lines}

**Metrics snapshot (last 30 min)**
| Metric | Value |
|---|---|
| Invocations | {mtr['total_invokes']} |
| Errors | {mtr['total_errors']} |
| Error rate | {mtr['error_rate_pct']}% |
| Max duration | {mtr['max_duration_ms']}ms |
| Throttles | {mtr['total_throttles']} |

---

### 🧠 Claude's Diagnosis
**Root cause:** {diagnosis.get('root_cause', '—')}

**Confidence:** `{diagnosis.get('confidence', '—')}`

**Reasoning:**
{reasoning}

---

### 🔧 Proposed Fix
**{diagnosis.get('fix_description', '—')}**

| Parameter | Before | After |
|---|---|---|
| Timeout | `{old_timeout}s` | `{new_timeout}s` |
| Memory | `{old_memory}MB` | `{new_memory}MB` |

**Risk:** `{diagnosis.get('risk', '—')}` — {diagnosis.get('risk_reason', '')}

---

### ✅ Outcome
{outcome_section}

---

### 🔍 Next Steps
- [ ] Re-invoke Lambda to confirm it no longer times out
- [ ] Monitor CloudWatch for 30 min post-fix
- [ ] Review and merge this PR once verified

---
*Auto-generated by [self-healing-starter](https://github.com/{repo_placeholder}) · do not edit manually*
""".replace("{repo_placeholder}", GITHUB_REPO)


# ── Public API ────────────────────────────────────────────────────────────────

def open_fix_pr(
    detection:  dict,
    diagnosis:  dict,
    fix_result: dict,
    outcome:    str = "applied",   # "applied" | "rejected" | "pending"
    repo:       str = "",
    base_branch:str = "",
) -> dict:
    """
    Main entry point. Call this after a self-healing event.

    Returns:
        {
            "success": bool,
            "pr_url":  str,         # HTML URL of the opened PR
            "branch":  str,         # name of the fix branch
            "message": str,         # human-readable status
        }
    """
    repo        = repo        or GITHUB_REPO
    base_branch = base_branch or BASE_BRANCH

    if not GITHUB_TOKEN:
        return {"success": False, "pr_url": "", "branch": "", "message": "GITHUB_TOKEN not set"}
    if not repo:
        return {"success": False, "pr_url": "", "branch": "", "message": "GITHUB_REPO not set"}

    fn         = detection["function_name"]
    issue_type = (detection["issues"][0]["type"] if detection.get("issues") else "unknown").lower()
    timestamp  = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch     = f"fix/lambda-{issue_type}-{timestamp}"

    try:
        # 1. Branch off base
        base_sha = _get_base_sha(repo, base_branch)
        _create_branch(repo, branch, base_sha)

        # 2. Commit updated lambda_config.json
        params     = diagnosis.get("fix_params", {})
        new_config = {
            "function_name": fn,
            "timeout":       params.get("timeout") or fix_result.get("new_timeout") or detection["config"]["timeout"],
            "memory":        params.get("memory")  or fix_result.get("new_memory")  or detection["config"]["memory"],
            "runtime":       detection["config"]["runtime"],
            "fix_applied_at": timestamp,
            "fix_action":    diagnosis.get("fix_action"),
            "root_cause":    diagnosis.get("root_cause"),
        }
        _upsert_file(
            repo    = repo,
            branch  = branch,
            path    = "lambda_config.json",
            content = json.dumps(new_config, indent=2),
            message = f"fix(lambda): auto-heal {issue_type} on {fn} [{timestamp}]",
        )

        # 3. Open PR
        title  = f"🤖 fix(lambda): auto-heal {issue_type} on `{fn}`"
        body = _build_pr_body(detection, diagnosis, fix_result, outcome, repo=repo)
        pr     = _open_pr(repo, title, body, head=branch, base=base_branch)
        pr_url = pr.get("html_url", "")

        return {
            "success": True,
            "pr_url":  pr_url,
            "branch":  branch,
            "message": f"PR opened: {pr_url}",
        }

    except Exception as e:
        return {
            "success": False,
            "pr_url":  "",
            "branch":  branch,
            "message": str(e),
        }