"""
pr_agent.py
Opens a GitHub PR as the approval gate for self-healing.

Flow:
  1. Issue detected + Claude diagnosis ready
  2. Human reviews proposed fix in dashboard
  3. Human clicks "Approve & Open PR"
  4. This module creates branch + commits lambda_config.json + opens PR
  5. Team reviews and merges PR on GitHub
  6. GitHub Action (apply_fix.yml) triggers and applies fix to Lambda

Requirements (in .env or Streamlit secrets):
  GITHUB_TOKEN  — personal access token with repo scope
  GITHUB_REPO   — e.g. "abiramikannanofficial-dotcom/self-healing-starter"
  GITHUB_BRANCH — base branch to PR against (default: "develop")
"""

import os
import json
import base64
import requests
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()

GITHUB_API   = "https://api.github.com"
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO  = os.getenv("GITHUB_REPO", "")
BASE_BRANCH  = os.getenv("GITHUB_BRANCH", "develop")


def _headers():
    return {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept":        "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _raise(resp, context=""):
    if not resp.ok:
        raise RuntimeError(
            f"GitHub API error ({context}): {resp.status_code} — {resp.text[:300]}"
        )


def _get_base_sha(repo: str, branch: str) -> str:
    r = requests.get(f"{GITHUB_API}/repos/{repo}/git/ref/heads/{branch}", headers=_headers())
    _raise(r, "get_base_sha")
    return r.json()["object"]["sha"]


def _create_branch(repo: str, new_branch: str, sha: str):
    payload = {"ref": f"refs/heads/{new_branch}", "sha": sha}
    r = requests.post(f"{GITHUB_API}/repos/{repo}/git/refs", headers=_headers(), json=payload)
    if r.status_code == 422 and "already exists" in r.text:
        return
    _raise(r, "create_branch")


def _get_file_sha(repo: str, path: str, branch: str):
    r = requests.get(
        f"{GITHUB_API}/repos/{repo}/contents/{path}",
        headers=_headers(),
        params={"ref": branch},
    )
    if r.status_code == 404:
        return None
    _raise(r, "get_file_sha")
    return r.json().get("sha")


def _upsert_file(repo: str, branch: str, path: str, content: str, message: str):
    existing_sha = _get_file_sha(repo, path, branch)
    payload = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch":  branch,
    }
    if existing_sha:
        payload["sha"] = existing_sha
    r = requests.put(
        f"{GITHUB_API}/repos/{repo}/contents/{path}",
        headers=_headers(),
        json=payload,
    )
    _raise(r, "upsert_file")


def _open_pr(repo: str, title: str, body: str, head: str, base: str) -> dict:
    payload = {"title": title, "body": body, "head": head, "base": base}
    r = requests.post(f"{GITHUB_API}/repos/{repo}/pulls", headers=_headers(), json=payload)
    _raise(r, "open_pr")
    return r.json()


def _build_pr_body(detection: dict, diagnosis: dict, repo: str) -> str:
    fn     = detection["function_name"]
    cfg    = detection["config"]
    mtr    = detection["metrics"]
    issues = detection.get("issues", [])
    params = diagnosis.get("fix_params", {})

    issue_lines = "\n".join(
        f"- `[{i['severity']}]` **{i['type']}** — {i['detail']}" for i in issues
    ) or "- None"

    reasoning = "\n".join(
        f"{idx+1}. {step}" for idx, step in enumerate(diagnosis.get("reasoning", []))
    )

    old_timeout = cfg.get("timeout", "?")
    old_memory  = cfg.get("memory",  "?")
    new_timeout = params.get("timeout") or old_timeout
    new_memory  = params.get("memory")  or old_memory
    timestamp   = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""## 🤖 Self-Healing — Proposed Fix

> Generated by the Agentic DevOps dashboard · {timestamp}
> **Merging this PR will automatically apply the fix to Lambda via GitHub Actions.**

---

### 📋 Function
| Field | Value |
|---|---|
| Name | `{fn}` |
| Runtime | `{cfg.get('runtime', '?')}` |
| Last modified | `{cfg.get('last_modified', '?')}` |

---

### ⚠️ Detected Issues
{issue_lines}

**Metrics snapshot (last 30 min)**
| Metric | Value |
|---|---|
| Invocations | {mtr['total_invokes']} |
| Errors | {mtr['total_errors']} |
| Error rate | {mtr['error_rate_pct']}% |
| Max duration | {mtr['max_duration_ms']}ms |
| Throttles | {mtr['total_throttles']} |

---

### 🧠 Claude's Diagnosis
**Root cause:** {diagnosis.get('root_cause', '—')}

**Confidence:** `{diagnosis.get('confidence', '—')}`

**Reasoning:**
{reasoning}

---

### 🔧 Proposed Fix
**{diagnosis.get('fix_description', '—')}**

| Parameter | Before | After |
|---|---|---|
| Timeout | `{old_timeout}s` | `{new_timeout}s` |
| Memory | `{old_memory}MB` | `{new_memory}MB` |

**Risk:** `{diagnosis.get('risk', '—')}` — {diagnosis.get('risk_reason', '')}

---

### ✅ To Apply
- [ ] Review the diagnosis and proposed fix above
- [ ] Merge this PR — GitHub Actions will update the Lambda automatically
- [ ] Monitor CloudWatch for 30 min post-fix
- [ ] Re-invoke Lambda to confirm it no longer times out

---
*Auto-generated by [self-healing-starter](https://github.com/{repo}) · do not edit manually*
"""


def open_fix_pr(
    detection:   dict,
    diagnosis:   dict,
    repo:        str = "",
    base_branch: str = "",
) -> dict:
    """
    Opens a PR with the proposed fix. Does NOT apply the fix itself.
    The fix is applied when the PR is merged via GitHub Actions.
    """
    repo        = repo        or GITHUB_REPO
    base_branch = base_branch or BASE_BRANCH

    if not GITHUB_TOKEN:
        return {"success": False, "pr_url": "", "branch": "", "message": "GITHUB_TOKEN not set"}
    if not repo:
        return {"success": False, "pr_url": "", "branch": "", "message": "GITHUB_REPO not set"}

    fn         = detection["function_name"]
    issue_type = (detection["issues"][0]["type"] if detection.get("issues") else "unknown").lower()
    timestamp  = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch     = f"fix/lambda-{issue_type}-{timestamp}"

    try:
        base_sha = _get_base_sha(repo, base_branch)
        _create_branch(repo, branch, base_sha)

        params     = diagnosis.get("fix_params", {})
        new_config = {
            "function_name": fn,
            "timeout":       params.get("timeout") or detection["config"]["timeout"],
            "memory":        params.get("memory")  or detection["config"]["memory"],
            "runtime":       detection["config"]["runtime"],
            "proposed_at":   timestamp,
            "fix_action":    diagnosis.get("fix_action"),
            "root_cause":    diagnosis.get("root_cause"),
            "confidence":    diagnosis.get("confidence"),
        }
        _upsert_file(
            repo    = repo,
            branch  = branch,
            path    = "lambda_config.json",
            content = json.dumps(new_config, indent=2),
            message = f"fix(lambda): propose auto-heal {issue_type} on {fn} [{timestamp}]",
        )

        title = f"🤖 fix(lambda): auto-heal {issue_type} on `{fn}`"
        body  = _build_pr_body(detection, diagnosis, repo)
        pr    = _open_pr(repo, title, body, head=branch, base=base_branch)

        return {
            "success": True,
            "pr_url":  pr.get("html_url", ""),
            "branch":  branch,
            "message": f"PR opened: {pr.get('html_url', '')}",
        }

    except Exception as e:
        return {
            "success": False,
            "pr_url":  "",
            "branch":  branch,
            "message": str(e),
        }